//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate-measurement-catalog.mjs. Do not edit directly.

import { deepFreeze } from '../core/index.js'

export const groveFhirContractVersion = '0.2.0' as const

export const groveFhirVersion = '4.0.1' as const

const groveConnectedHealthPackageMetadataValue = {
  fhirVersion: '4.0.1',
  version: '0.2.0',
  packageId: 'org.grovealliance.fhir.connected-health',
  canonical: 'https://grovealliance.org/fhir/connected-health',
  dependencies: [
    'org.grovealliance.fhir.mobile#0.2.0',
    'org.grovealliance.fhir.sensor#0.2.0',
  ],
} as const

export const groveConnectedHealthPackageMetadata: typeof groveConnectedHealthPackageMetadataValue =
  deepFreeze(groveConnectedHealthPackageMetadataValue)

const groveConnectedHealthPackageCanonicalsValue = {
  mobile: 'https://grovealliance.org/fhir/mobile',
  sensor: 'https://grovealliance.org/fhir/sensor',
  'connected-health': 'https://grovealliance.org/fhir/connected-health',
} as const

export const groveConnectedHealthPackageCanonicals: typeof groveConnectedHealthPackageCanonicalsValue =
  deepFreeze(groveConnectedHealthPackageCanonicalsValue)

const groveConnectedHealthProfileCanonicalsValue = {
  'grove-mobile-active-energy':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-active-energy',
  'grove-mobile-basal-body-temperature':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-basal-body-temperature',
  'grove-mobile-blood-pressure':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-blood-pressure',
  'grove-mobile-body-height':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-height',
  'grove-mobile-body-temperature':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-temperature',
  'grove-mobile-body-weight':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-weight',
  'grove-mobile-distance':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-distance',
  'grove-mobile-heart-rate':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-heart-rate',
  'grove-mobile-oxygen-saturation':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-oxygen-saturation',
  'grove-mobile-respiratory-rate':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-respiratory-rate',
  'grove-mobile-sleep-duration':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-duration',
  'grove-mobile-sleep-stage':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-stage',
  'grove-mobile-step-count':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-step-count',
  'grove-application-device':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-application-device',
  'grove-mobile-exchange-bundle':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-exchange-bundle',
  'grove-recording-device':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-recording-device',
  'grove-sensor-recording-document':
    'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
  'connected-health-conversion-provenance':
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-conversion-provenance',
  'connected-health-observation':
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-observation',
  'connected-health-recording-document':
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
} as const

export const groveConnectedHealthProfileCanonicals: typeof groveConnectedHealthProfileCanonicalsValue =
  deepFreeze(groveConnectedHealthProfileCanonicalsValue)

const connectedHealthAdapterCatalogValue = {
  schemaVersion: 1,
  fhirVersion: '4.0.1',
  version: '0.2.0',
  packageId: 'org.grovealliance.fhir.connected-health',
  canonical: 'https://grovealliance.org/fhir/connected-health',
  adapterProfile:
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-observation',
  sourceTypeExtension: {
    url: 'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-source-type',
    codeSystem:
      'https://grovealliance.org/fhir/connected-health/CodeSystem/connected-health-source-type',
    element:
      'Observation.extension.valueCode or DocumentReference.extension.valueCode',
    cardinality: 'exactly one',
    codeRule:
      "provider id + '/' + exact source token; the atomic Withings blood-pressure output uses withings/getmeas:9+10",
    rule: 'Every admitted output makes the exact catalog dispatch token recoverable without reversing its source-record digest.',
  },
  recordingDocument: {
    sourceNeutralProfile:
      'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
    adapterProfile:
      'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
    claimMode: 'exactly-source-neutral-plus-adapter',
    outputDiscriminator: 'native-recording',
    encoding: 'caller-supplied exact already-obtained provider bytes',
  },
  rawPayloadAdmission: {
    contract:
      'https://grovealliance.org/fhir/sensor#recording-document.payloadAdmission',
    allowedAssertions: [
      'caller-authorized-opaque-payload',
      'verified-sanitized-input',
    ],
    failureRule:
      'The producer fails closed before emission unless the caller supplies exactly one assertion.',
    notFHIRAuthorization: true,
  },
  conversionProvenanceProfile:
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-conversion-provenance',
  statusVocabulary: [
    'supported',
    'mapped-standard',
    'provider-specific',
    'deferred',
    'intentionally-unsupported',
  ],
  statusDefinitions: {
    supported:
      'Version 0.2.0 defines an exact conversion to every shared profile listed for the source element.',
    'mapped-standard':
      'Version 0.2.0 admits only the listed source-neutral Sensor recording contract and does not assert a scalar clinical result.',
    'provider-specific':
      'The source element is inventoried but has no shared Mobile semantic profile in version 0.2.0.',
    deferred:
      'A plausible shared mapping is known, but the source evidence, time semantics, or result shape is insufficient for a conformant version 0.2.0 output.',
    'intentionally-unsupported':
      'Version 0.2.0 deliberately refuses a normalized conversion because doing so would be misleading or diagnostic-adjacent.',
  },
  sourceEvidence: {
    accessed: '2026-08-20',
    scope:
      'Exact provider data-type tokens and consumed fields frozen in providers[].sourceTypes; conversion operates only on already-obtained payloads and defines no provider fetching.',
    tokenBinding:
      'Each providers[].sourceTypes[].token and elements[].path is part of the exact v0.2.0 consumed source surface.',
    providers: [
      {
        id: 'google-health-api',
        surface: 'Google Health API REST',
        version: 'v4',
        documentation: [
          'https://developers.google.com/health/data-types',
          'https://developers.google.com/health/reference/rest/v4/users.dataTypes.dataPoints',
        ],
      },
      {
        id: 'oura',
        surface: 'Oura API',
        version: '2.0',
        documentation: ['https://cloud.ouraring.com/v2/docs'],
      },
      {
        id: 'withings',
        surface: 'Withings Health Data API',
        version: '2.0',
        documentation: [
          'https://developer.withings.com/api-reference/',
          'https://developer.withings.com/developer-guide/v3/integration-guide/public-health-data-api/data-api/all-available-health-data/',
        ],
      },
    ],
  },
  identity: {
    canonicalization:
      'RFC 8785/JCS serialization of arrays and Unicode scalar-value strings; UTF-8; non-ASCII unescaped; short JSON escapes for quote, reverse solidus, backspace, tab, line feed, form feed, and carriage return; other U+0000 through U+001F as lowercase \\u00xx; invalid Unicode surrogates rejected',
    digest:
      'SHA-256 over the UTF-8 preimage, lowercase hexadecimal, prefixed with v1:',
    providerAccountIdentifier: {
      requirement:
        'A complete deployment-scoped pseudonymous Identifier pair. It must be stable for the provider-account scope needed for deduplication.',
      prohibitedByDefault: [
        'vendor email address',
        'vendor account id',
        'vendor member id',
        'OAuth subject or token',
      ],
      exception:
        'A raw vendor account value may be used only when an explicit deployment privacy policy authorizes that disclosure; this package grants no such authorization.',
      emission:
        'Digest input only; the pair is not copied to the emitted clinical resource.',
    },
    sourceNativeId: {
      requirement:
        'The exact stable native record or group key supplied by the already-obtained provider payload.',
      emission:
        'Digest input only for FHIR metadata: the raw value must not appear in Resource.id, Identifier.value, extensions, attachment URL/title, or Provenance text. Opaque caller-supplied attachment bytes are not semantically inspected and require separate deployment authorization and minimization.',
    },
    derivedDigest: {
      meaning:
        'A deterministic business identity for deduplication and reference resolution.',
      notAuthorization: true,
      rule: 'It is not an access token, credential, proof of authorization, or permission to fetch provider data.',
    },
    sourceRecord: {
      system:
        'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-source-record-id',
      preimage: [
        'providerCode',
        'providerAccountIdentifier.system',
        'providerAccountIdentifier.value',
        'sourceType',
        'sourceNativeId',
      ],
    },
    output: {
      system:
        'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-output-id',
      preimage: [
        'sourceRecordIdentifier.system',
        'sourceRecordIdentifier.value',
        'outputDiscriminator',
      ],
      outputDiscriminatorRule: {
        ordinarySupportedMeasurement:
          'the exact measurementId string from the supported element mapping',
        groupedMapping:
          'the exact outputDiscriminator declared on that groupedMappings row',
        mappedStandardRaw: 'native-recording',
        noFallback: true,
      },
    },
    conversion: {
      system:
        'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-conversion-id',
      preimage: ['sortedSourceRecordIdentifiers', 'positiveEventSequence'],
    },
    exchange: {
      system:
        'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-exchange-id',
      preimage: ['sortedSourceRecordIdentifiers', 'positiveEventSequence'],
    },
    vectors: [
      {
        role: 'sourceRecord',
        inputs: [
          'google-health-api',
          'https://provider.example.org/accounts',
          'account-001',
          'steps',
          'steps-2026-08-20T16:00:00Z',
        ],
        canonicalPreimage:
          '["google-health-api","https://provider.example.org/accounts","account-001","steps","steps-2026-08-20T16:00:00Z"]',
        identifierValue:
          'v1:c698f75a1901b494c9c5a2107a88708dccbd1d5556fc5c85f364c536164fa383',
      },
      {
        role: 'output',
        inputs: [
          'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-source-record-id',
          'v1:c698f75a1901b494c9c5a2107a88708dccbd1d5556fc5c85f364c536164fa383',
          'step-count',
        ],
        canonicalPreimage:
          '["https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-source-record-id","v1:c698f75a1901b494c9c5a2107a88708dccbd1d5556fc5c85f364c536164fa383","step-count"]',
        identifierValue:
          'v1:58ec980e4eaa0bd8ca600043db5446c21a13482b064fffbb44469046f1876406',
      },
      {
        role: 'sourceRecord',
        inputs: [
          'google-health-api',
          'https://provider.example.org/accounts',
          'account-001',
          'heart-rate',
          'heart-rate-2026-08-20',
        ],
        canonicalPreimage:
          '["google-health-api","https://provider.example.org/accounts","account-001","heart-rate","heart-rate-2026-08-20"]',
        identifierValue:
          'v1:e9174b24826045a9d8bfb85888baea27526e626b5049f7c8d0cb6a1479c965d5',
      },
      {
        role: 'output',
        inputs: [
          'https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-source-record-id',
          'v1:e9174b24826045a9d8bfb85888baea27526e626b5049f7c8d0cb6a1479c965d5',
          'native-recording',
        ],
        canonicalPreimage:
          '["https://grovealliance.org/fhir/connected-health/NamingSystem/connected-health-source-record-id","v1:e9174b24826045a9d8bfb85888baea27526e626b5049f7c8d0cb6a1479c965d5","native-recording"]',
        identifierValue:
          'v1:277b888059d003e8c0fe6b6d131b09a703bf6bc56f9be37fb8bb97582cf98e7a',
      },
      {
        role: 'sourceRecord',
        inputs: [
          'oura',
          'https://provider.example.org/accounts',
          'café\n"\\',
          'sleep',
          'résumé-\u0001',
        ],
        canonicalUtf8Hex:
          '5b226f757261222c2268747470733a2f2f70726f76696465722e6578616d706c652e6f72672f6163636f756e7473222c22636166c3a95c6e5c225c5c222c22736c656570222c2272c3a973756dc3a92d5c7530303031225d',
        identifierValue:
          'v1:05890004d78c74e768503a2aa14e91a66c5f815b41937a2de626fd167d6c59de',
      },
    ],
    resourceIdPolicy:
      'Resource.id is optional and repository-assigned; no provider-native key or digest is copied into Resource.id.',
  },
  providers: [
    {
      id: 'google-health-api',
      title: 'Google Health API',
      sourceTypeCount: 18,
      sourceTypes: [
        {
          token: 'steps',
          status: 'supported',
          elements: [
            {
              path: 'steps.count',
              status: 'supported',
              measurementIds: ['step-count'],
              unitConversion: 'integer count to UCUM {steps}',
              effective: 'steps.interval',
            },
          ],
        },
        {
          token: 'distance',
          status: 'supported',
          elements: [
            {
              path: 'distance.millimeters',
              status: 'supported',
              measurementIds: ['distance'],
              unitConversion: 'millimetres divided by 1000 to UCUM m',
              effective: 'distance.interval',
            },
          ],
        },
        {
          token: 'active-energy-burned',
          status: 'supported',
          elements: [
            {
              path: 'activeEnergyBurned.kcal',
              status: 'supported',
              measurementIds: ['active-energy'],
              unitConversion: 'identity UCUM kcal',
              effective: 'activeEnergyBurned.interval',
            },
          ],
        },
        {
          token: 'weight',
          status: 'supported',
          elements: [
            {
              path: 'weight.weightGrams',
              status: 'supported',
              measurementIds: ['body-weight'],
              unitConversion: 'grams divided by 1000 to UCUM kg',
              effective: 'weight.sampleTime.physicalTime',
            },
          ],
        },
        {
          token: 'body-fat',
          status: 'provider-specific',
          elements: [
            {
              path: 'bodyFat.percentage',
              status: 'provider-specific',
              reason:
                'No shared Mobile body-fat profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'height',
          status: 'supported',
          elements: [
            {
              path: 'height.heightMillimeters',
              status: 'supported',
              measurementIds: ['body-height'],
              unitConversion: 'millimetres divided by 10 to UCUM cm',
              effective: 'height.sampleTime.physicalTime',
            },
          ],
        },
        {
          token: 'vo2-max',
          status: 'provider-specific',
          elements: [
            {
              path: 'vo2Max.vo2Max',
              status: 'provider-specific',
              reason:
                'No shared Mobile VO2 max profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'daily-oxygen-saturation',
          status: 'deferred',
          elements: [
            {
              path: 'dailyOxygenSaturation.averagePercentage',
              status: 'deferred',
              reason:
                'A civil-date daily average is not a point-in-time pulse-oximetry result and cannot satisfy the shared oxygen-saturation effective-time semantics without invention.',
            },
          ],
        },
        {
          token: 'heart-rate-variability',
          status: 'provider-specific',
          elements: [
            {
              path: 'heartRateVariability.rootMeanSquareOfSuccessiveDifferencesMilliseconds',
              status: 'provider-specific',
              reason:
                'RMSSD is distinct from SDNN and no shared Mobile HRV profile exists in version 0.2.0.',
            },
            {
              path: 'heartRateVariability.standardDeviationMilliseconds',
              status: 'provider-specific',
              reason: 'No shared Mobile HRV profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'daily-resting-heart-rate',
          status: 'provider-specific',
          elements: [
            {
              path: 'dailyRestingHeartRate.beatsPerMinute',
              status: 'provider-specific',
              reason:
                'Resting heart rate is a daily aggregate with semantics distinct from the shared point heart-rate profile.',
            },
          ],
        },
        {
          token: 'daily-respiratory-rate',
          status: 'deferred',
          elements: [
            {
              path: 'dailyRespiratoryRate.breathsPerMinute',
              status: 'deferred',
              reason:
                'A civil-date daily average cannot satisfy the shared point respiratory-rate effective-time semantics without invention.',
            },
          ],
        },
        {
          token: 'blood-glucose',
          status: 'deferred',
          elements: [
            {
              path: 'bloodGlucose.bloodGlucoseMilligramsPerDeciliter',
              status: 'deferred',
              reason:
                'The consumed source shape has no specimen evidence, so none of the four Health Connect-only specimen-specific glucose profiles can be selected.',
            },
          ],
        },
        {
          token: 'core-body-temperature',
          status: 'supported',
          elements: [
            {
              path: 'coreBodyTemperature.temperatureCelsius',
              status: 'supported',
              measurementIds: ['body-temperature'],
              unitConversion: 'identity UCUM Cel',
              effective: 'coreBodyTemperature.sampleTime.physicalTime',
            },
          ],
        },
        {
          token: 'floors',
          status: 'provider-specific',
          elements: [
            {
              path: 'floors.count',
              status: 'provider-specific',
              reason:
                'No shared Mobile floors-climbed profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'basal-energy-burned',
          status: 'provider-specific',
          elements: [
            {
              path: 'basalEnergyBurned.kcal',
              status: 'provider-specific',
              reason:
                'Basal energy is not active energy and has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'sleep',
          status: 'supported',
          elements: [
            {
              path: 'sleep.summary.minutesAsleep',
              status: 'supported',
              measurementIds: ['sleep-duration'],
              unitConversion: 'minutes divided by 60 to UCUM h',
              effective: 'sleep.interval',
            },
            {
              path: 'sleep.summary.stagesSummary[type=DEEP].minutes',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'sleep.summary.stagesSummary[type=REM].minutes',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'sleep.summary.stagesSummary[type=LIGHT].minutes',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'sleep.summary.stagesSummary[type=AWAKE].minutes',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
          ],
        },
        {
          token: 'exercise',
          status: 'provider-specific',
          elements: [
            {
              path: 'exercise.interval',
              status: 'provider-specific',
              reason:
                'Workout duration has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'heart-rate',
          status: 'mapped-standard',
          archiveDataType: 'heartRate',
          raw: {
            sourceNeutralProfile:
              'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            adapterProfile:
              'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
            outputDiscriminator: 'native-recording',
          },
          elements: [
            {
              path: 'payload',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
              reason:
                'The source points may be irregular; retain the provider-native recording rather than resample or invent a uniform SampledData period.',
            },
          ],
        },
      ],
    },
    {
      id: 'oura',
      title: 'Oura',
      sourceTypeCount: 8,
      sourceTypes: [
        {
          token: 'daily_activity',
          status: 'supported',
          elements: [
            {
              path: 'steps',
              status: 'supported',
              measurementIds: ['step-count'],
              unitConversion: 'integer count to UCUM {steps}',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
            {
              path: 'active_calories',
              status: 'supported',
              measurementIds: ['active-energy'],
              unitConversion: 'identity UCUM kcal',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
            {
              path: 'equivalent_walking_distance',
              status: 'supported',
              measurementIds: ['distance'],
              unitConversion: 'identity UCUM m',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
          ],
        },
        {
          token: 'sleep',
          status: 'supported',
          elements: [
            {
              path: 'total_sleep_duration',
              status: 'supported',
              measurementIds: ['sleep-duration'],
              unitConversion: 'seconds divided by 3600 to UCUM h',
              effective:
                'bedtime_start through bedtime_end; output deferred when either boundary is absent',
            },
            {
              path: 'deep_sleep_duration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'rem_sleep_duration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'light_sleep_duration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'awake_time',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
            {
              path: 'lowest_heart_rate',
              status: 'provider-specific',
              reason:
                'A sleep-session minimum is not a point heart-rate measurement.',
            },
            {
              path: 'average_hrv',
              status: 'provider-specific',
              reason: 'No shared Mobile HRV profile exists in version 0.2.0.',
            },
            {
              path: 'average_breath',
              status: 'deferred',
              reason:
                'A session average cannot satisfy the shared point respiratory-rate effective-time semantics without invention.',
            },
          ],
        },
        {
          token: 'daily_spo2',
          status: 'deferred',
          elements: [
            {
              path: 'spo2_percentage.average',
              status: 'deferred',
              reason:
                'A daily average is not a point-in-time pulse-oximetry result.',
            },
          ],
        },
        {
          token: 'workout',
          status: 'provider-specific',
          elements: [
            {
              path: 'start_datetime/end_datetime',
              status: 'provider-specific',
              reason:
                'Workout duration has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'vO2_max',
          status: 'provider-specific',
          elements: [
            {
              path: 'vo2_max',
              status: 'provider-specific',
              reason:
                'No shared Mobile VO2 max profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'daily_cardiovascular_age',
          status: 'provider-specific',
          elements: [
            {
              path: 'vascular_age',
              status: 'provider-specific',
              reason:
                'A provider-computed cardiovascular age is not a physiological measurement shared across sources.',
            },
          ],
        },
        {
          token: 'daily_readiness',
          status: 'provider-specific',
          elements: [
            {
              path: 'score',
              status: 'provider-specific',
              reason:
                'A provider-computed readiness score is not a physiological measurement shared across sources.',
            },
          ],
        },
        {
          token: 'heartrate',
          status: 'mapped-standard',
          archiveDataType: 'heartRate',
          raw: {
            sourceNeutralProfile:
              'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            adapterProfile:
              'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
            outputDiscriminator: 'native-recording',
          },
          elements: [
            {
              path: 'payload',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
              reason:
                'Timestamped points may be irregular; retain the provider-native recording rather than resample or invent a uniform SampledData period.',
            },
          ],
        },
      ],
    },
    {
      id: 'withings',
      title: 'Withings',
      sourceTypeCount: 42,
      groupedMappings: [
        {
          token: 'getmeas:9+10',
          status: 'supported',
          members: ['getmeas:9', 'getmeas:10'],
          sourceNativeId: 'the common measure-group grpid',
          measurementIds: ['blood-pressure'],
          outputDiscriminator: 'blood-pressure-panel',
          rule: 'Emit exactly one panel only when one type 9 value and one type 10 value occur in the same measure group; otherwise emit neither component as a normalized Observation. Use getmeas:9+10, not either member token, in the source-record identity preimage.',
        },
      ],
      sourceTypes: [
        {
          token: 'getmeas:1',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['body-weight'],
              unitConversion: 'provider SI value to UCUM kg',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:4',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['body-height'],
              unitConversion: 'provider SI value to UCUM cm',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:6',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'No shared Mobile body-fat profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:9',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['blood-pressure'],
              component: 'diastolic',
              groupedMapping: 'getmeas:9+10',
              unitConversion: 'provider SI value to UCUM mm[Hg]',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:10',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['blood-pressure'],
              component: 'systolic',
              groupedMapping: 'getmeas:9+10',
              unitConversion: 'provider SI value to UCUM mm[Hg]',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:11',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['heart-rate'],
              unitConversion: 'provider value to UCUM /min',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:54',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['oxygen-saturation'],
              unitConversion: 'provider value to UCUM %',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:71',
          status: 'supported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'supported',
              measurementIds: ['body-temperature'],
              unitConversion: 'provider value to UCUM Cel',
              effective: 'measure group date',
            },
          ],
        },
        {
          token: 'getmeas:123',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'No shared Mobile VO2 max profile exists in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:155',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'A provider-computed cardiovascular age is not a physiological measurement shared across sources.',
            },
          ],
        },
        {
          token: 'getactivity:steps',
          status: 'supported',
          elements: [
            {
              path: 'steps',
              status: 'supported',
              measurementIds: ['step-count'],
              unitConversion: 'integer count to UCUM {steps}',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
          ],
        },
        {
          token: 'getactivity:distance',
          status: 'supported',
          elements: [
            {
              path: 'distance',
              status: 'supported',
              measurementIds: ['distance'],
              unitConversion: 'identity UCUM m',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
          ],
        },
        {
          token: 'getactivity:calories',
          status: 'supported',
          elements: [
            {
              path: 'calories',
              status: 'supported',
              measurementIds: ['active-energy'],
              unitConversion: 'identity UCUM kcal',
              effective:
                'the source civil day represented as a complete day Period; midpoint substitution is forbidden',
            },
          ],
        },
        {
          token: 'getsummary:deepsleepduration',
          status: 'provider-specific',
          elements: [
            {
              path: 'data.deepsleepduration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
          ],
        },
        {
          token: 'getsummary:remsleepduration',
          status: 'provider-specific',
          elements: [
            {
              path: 'data.remsleepduration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
          ],
        },
        {
          token: 'getsummary:lightsleepduration',
          status: 'provider-specific',
          elements: [
            {
              path: 'data.lightsleepduration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
          ],
        },
        {
          token: 'getsummary:wakeupduration',
          status: 'provider-specific',
          elements: [
            {
              path: 'data.wakeupduration',
              status: 'provider-specific',
              reason:
                'A stage-duration summary has no stage interval and is not a shared sleep-stage Observation.',
            },
          ],
        },
        {
          token: 'getsummary:hr_average',
          status: 'provider-specific',
          elements: [
            {
              path: 'data.hr_average',
              status: 'provider-specific',
              reason:
                'A sleep-session average is not a point heart-rate measurement.',
            },
          ],
        },
        {
          token: 'getsummary:rr_average',
          status: 'deferred',
          elements: [
            {
              path: 'data.rr_average',
              status: 'deferred',
              reason:
                'A sleep-session average cannot satisfy the shared point respiratory-rate effective-time semantics without invention.',
            },
          ],
        },
        {
          token: 'getworkouts:interval',
          status: 'provider-specific',
          elements: [
            {
              path: 'startdate/enddate',
              status: 'provider-specific',
              reason:
                'Workout duration has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'activityIntraday',
          status: 'mapped-standard',
          archiveDataType: 'activityIntraday',
          raw: {
            sourceNeutralProfile:
              'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            adapterProfile:
              'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
            outputDiscriminator: 'native-recording',
          },
          elements: [
            {
              path: 'steps',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'calories',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'distance',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'elevation',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'heart_rate',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'spo2_auto',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
          ],
        },
        {
          token: 'sleepIntraday',
          status: 'mapped-standard',
          archiveDataType: 'sleepIntraday',
          raw: {
            sourceNeutralProfile:
              'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            adapterProfile:
              'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-recording-document',
            outputDiscriminator: 'native-recording',
          },
          elements: [
            {
              path: 'hr',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'rr',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'snoring',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'sdnn_1',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
            {
              path: 'rmssd',
              status: 'mapped-standard',
              sensorProfile:
                'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
            },
          ],
        },
        {
          token: 'getmeas:5',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Fat-free mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:8',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason: 'Fat mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:73',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Skin temperature is not relabeled as core or generic body temperature.',
            },
          ],
        },
        {
          token: 'getmeas:76',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Muscle mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:77',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Hydration has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:88',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Bone mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:91',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Pulse-wave velocity has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:130',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value',
              status: 'intentionally-unsupported',
              reason:
                'An AFib classification is diagnostic-adjacent and is not represented as an untyped scalar Observation.',
            },
          ],
        },
        {
          token: 'getmeas:135',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'intentionally-unsupported',
              reason:
                'A QRS interval requires an ECG-specific interpretation contract not present in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:136',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'intentionally-unsupported',
              reason:
                'A PR interval requires an ECG-specific interpretation contract not present in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:137',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'intentionally-unsupported',
              reason:
                'A QT interval requires an ECG-specific interpretation contract not present in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:138',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'intentionally-unsupported',
              reason:
                'A corrected QT interval requires an ECG-specific interpretation contract not present in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:139',
          status: 'intentionally-unsupported',
          elements: [
            {
              path: 'measure.value',
              status: 'intentionally-unsupported',
              reason:
                'An AFib classification is diagnostic-adjacent and is not represented as an untyped scalar Observation.',
            },
          ],
        },
        {
          token: 'getmeas:167',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Nerve health score has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:168',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Extracellular water has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:169',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Intracellular water has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:170',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Visceral fat has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:174',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Segmental fat mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:175',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Segmental muscle mass has no shared Mobile profile in version 0.2.0.',
            },
          ],
        },
        {
          token: 'getmeas:196',
          status: 'provider-specific',
          elements: [
            {
              path: 'measure.value*10^unit',
              status: 'provider-specific',
              reason:
                'Electrodermal activity has no shared Mobile scalar profile in version 0.2.0.',
            },
          ],
        },
      ],
    },
  ],
} as const

export const connectedHealthAdapterCatalog: typeof connectedHealthAdapterCatalogValue =
  deepFreeze(connectedHealthAdapterCatalogValue)

const connectedHealthScalarMappingsValue = {
  'google-health-api': {
    steps: {
      'step-count': 'step-count',
    },
    distance: {
      distance: 'distance',
    },
    'active-energy-burned': {
      'active-energy': 'active-energy',
    },
    weight: {
      'body-weight': 'body-weight',
    },
    height: {
      'body-height': 'body-height',
    },
    'core-body-temperature': {
      'body-temperature': 'body-temperature',
    },
    sleep: {
      'sleep-duration': 'sleep-duration',
    },
  },
  oura: {
    daily_activity: {
      'step-count': 'step-count',
      'active-energy': 'active-energy',
      distance: 'distance',
    },
    sleep: {
      'sleep-duration': 'sleep-duration',
    },
  },
  withings: {
    'getmeas:1': {
      'body-weight': 'body-weight',
    },
    'getmeas:4': {
      'body-height': 'body-height',
    },
    'getmeas:11': {
      'heart-rate': 'heart-rate',
    },
    'getmeas:54': {
      'oxygen-saturation': 'oxygen-saturation',
    },
    'getmeas:71': {
      'body-temperature': 'body-temperature',
    },
    'getactivity:steps': {
      'step-count': 'step-count',
    },
    'getactivity:distance': {
      distance: 'distance',
    },
    'getactivity:calories': {
      'active-energy': 'active-energy',
    },
    'getmeas:9+10': {
      'blood-pressure': 'blood-pressure-panel',
    },
  },
} as const

export const connectedHealthScalarMappings: typeof connectedHealthScalarMappingsValue =
  deepFreeze(connectedHealthScalarMappingsValue)

const connectedHealthRecordEffectiveRulesValue = {
  oura: {
    daily_activity: {
      kind: 'complete-civil-day-period',
      measurementIds: ['step-count', 'active-energy', 'distance'],
      outputsShareEffective: true,
    },
  },
  withings: {
    'getactivity:steps': {
      kind: 'complete-civil-day-period',
      measurementIds: ['step-count'],
      outputsShareEffective: true,
    },
    'getactivity:distance': {
      kind: 'complete-civil-day-period',
      measurementIds: ['distance'],
      outputsShareEffective: true,
    },
    'getactivity:calories': {
      kind: 'complete-civil-day-period',
      measurementIds: ['active-energy'],
      outputsShareEffective: true,
    },
  },
} as const

export const connectedHealthRecordEffectiveRules: typeof connectedHealthRecordEffectiveRulesValue =
  deepFreeze(connectedHealthRecordEffectiveRulesValue)

const connectedHealthRawMappingsValue = {
  'google-health-api': {
    'heart-rate': 'native-recording',
  },
  oura: {
    heartrate: 'native-recording',
  },
  withings: {
    activityIntraday: 'native-recording',
    sleepIntraday: 'native-recording',
  },
} as const

export const connectedHealthRawMappings: typeof connectedHealthRawMappingsValue =
  deepFreeze(connectedHealthRawMappingsValue)

export type ConnectedHealthScalarMappings = typeof connectedHealthScalarMappings

export type ConnectedHealthRecordEffectiveRules =
  typeof connectedHealthRecordEffectiveRules

export type ConnectedHealthRawMappings = typeof connectedHealthRawMappings
