//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate-measurement-catalog.mjs. Do not edit directly.

/* eslint-disable sonarjs/no-clear-text-protocols */

export const groveFhirPackageGraph = {
  schemaVersion: 1,
  fhirVersion: '4.0.1',
  version: '0.2.0',
  canonicalRoot: 'https://grovealliance.org/fhir',
  packages: [
    {
      source: 'mobile',
      packageId: 'org.grovealliance.fhir.mobile',
      canonical: 'https://grovealliance.org/fhir/mobile',
      dependencies: [],
      profiles: [
        'grove-application-device',
        'grove-mobile-active-energy',
        'grove-mobile-basal-body-temperature',
        'grove-mobile-blood-glucose',
        'grove-mobile-blood-pressure',
        'grove-mobile-bmi',
        'grove-mobile-body-height',
        'grove-mobile-body-temperature',
        'grove-mobile-body-weight',
        'grove-mobile-capillary-blood-glucose',
        'grove-mobile-conversion-provenance',
        'grove-mobile-distance',
        'grove-mobile-exchange-bundle',
        'grove-mobile-heart-rate',
        'grove-mobile-interstitial-glucose',
        'grove-mobile-observation',
        'grove-mobile-oxygen-saturation',
        'grove-mobile-respiratory-rate',
        'grove-mobile-serum-plasma-glucose',
        'grove-mobile-sleep-duration',
        'grove-mobile-sleep-stage',
        'grove-mobile-step-count',
        'grove-recording-device',
      ],
    },
    {
      source: 'questionnaire',
      packageId: 'org.grovealliance.fhir.questionnaire',
      canonical: 'https://grovealliance.org/fhir/questionnaire',
      dependencies: ['hl7.fhir.uv.sdc#4.0.0'],
      profiles: ['grove-questionnaire', 'grove-questionnaire-response'],
    },
    {
      source: 'sensor',
      packageId: 'org.grovealliance.fhir.sensor',
      canonical: 'https://grovealliance.org/fhir/sensor',
      dependencies: [
        'org.grovealliance.fhir.mobile#0.2.0',
        'hl7.fhir.uv.phd#2.0.0',
      ],
      profiles: [
        'grove-sensor-ecg-observation',
        'grove-sensor-recording-document',
        'grove-sensor-sampled-data-observation',
      ],
    },
    {
      source: 'healthkit',
      packageId: 'org.grovealliance.fhir.healthkit',
      canonical: 'https://grovealliance.org/fhir/healthkit',
      dependencies: [
        'org.grovealliance.fhir.mobile#0.2.0',
        'org.grovealliance.fhir.sensor#0.2.0',
      ],
      profiles: ['healthkit-observation'],
    },
    {
      source: 'health-connect',
      packageId: 'org.grovealliance.fhir.health-connect',
      canonical: 'https://grovealliance.org/fhir/health-connect',
      dependencies: ['org.grovealliance.fhir.mobile#0.2.0'],
      profiles: [
        'health-connect-conversion-provenance',
        'health-connect-observation',
      ],
    },
    {
      source: 'connected-health',
      packageId: 'org.grovealliance.fhir.connected-health',
      canonical: 'https://grovealliance.org/fhir/connected-health',
      dependencies: ['org.grovealliance.fhir.mobile#0.2.0'],
      profiles: [
        'connected-health-conversion-provenance',
        'connected-health-observation',
      ],
    },
  ],
} as const

export const groveFhirExchangeIdentity = {
  schemaVersion: 1,
  profile:
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-exchange-bundle',
  entryIdentifierExtension:
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-exchange-entry-identifier',
  fullUrlAlgorithm: {
    name: 'uuid-v5-jcs-identifier-v1',
    namespace: 'a9a39cf1-c944-5d15-a3c2-c395969ea101',
    input:
      'UTF-8 bytes of the RFC 8785 JSON Canonicalization Scheme serialization of exactly [system,value]',
    stringRules: {
      unicode:
        'system and value MUST contain only Unicode scalar values; isolated UTF-16 surrogates are rejected',
      escaping:
        'escape quotation mark and reverse solidus; use the two-character escapes \\b, \\t, \\n, \\f and \\r; encode every other U+0000 through U+001F control as lowercase \\u00xx; do not escape solidus or any other scalar value',
      encoding:
        'encode the resulting JSON text as UTF-8 without a byte-order mark',
      array:
        'quotation mark, serialized system, quotation mark, comma, quotation mark, serialized value, quotation mark; no whitespace',
    },
    output: 'urn:uuid:<lowercase RFC 4122 UUID version 5>',
  },
  resourceId: {
    role: 'repository logical id',
    required: false,
    sourceIdentityAllowed: false,
  },
  internalReferences: {
    containedReferencesAllowed: true,
    bundleEntryReferences: 'must use an entry fullUrl UUID URN',
    unresolvedUuidUrnsAllowed: false,
  },
  vectors: [
    {
      case: 'ascii',
      system: 'https://study.example.org/fhir/identifiers/mobile-observation',
      value: 'heart-rate-20260820-001',
      input:
        '["https://study.example.org/fhir/identifiers/mobile-observation","heart-rate-20260820-001"]',
      fullUrl: 'urn:uuid:cd27941b-2a75-5f7a-bd25-71e9480eac24',
    },
    {
      case: 'quotation-mark-and-reverse-solidus',
      system: 'https://example.org/"quoted"',
      value: 'back\\slash',
      input: '["https://example.org/\\"quoted\\"","back\\\\slash"]',
      fullUrl: 'urn:uuid:fe6c20ac-f147-5322-8804-c09d5c0f62d6',
    },
    {
      case: 'control-characters',
      system: 'https://example.org/control',
      value: 'line\nfeed\u0001',
      input: '["https://example.org/control","line\\nfeed\\u0001"]',
      fullUrl: 'urn:uuid:9a1a6b19-a138-5fdf-8954-68a3da142c64',
    },
    {
      case: 'non-ascii',
      system: 'https://例.example/識別子',
      value: 'café-東京',
      input: '["https://例.example/識別子","café-東京"]',
      fullUrl: 'urn:uuid:f1395804-98e2-5d14-a2f4-cbe93380ee7a',
    },
  ],
} as const

export const groveFhirProfileClaims = {
  schemaVersion: 1,
  fhirVersion: '4.0.1',
  version: '0.2.0',
  observationAdapterClaim: {
    cardinality: 2,
    members: [
      'exactly one shared measurement profile from catalog/measurement-catalog.json',
      'exactly one adapter profile listed below',
    ],
    inheritedProfilesAreNotDeclared: true,
    adapterProfiles: [
      'https://grovealliance.org/fhir/healthkit/StructureDefinition/healthkit-observation',
      'https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-observation',
      'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-observation',
    ],
    forbiddenExplicitProfiles: [
      'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-observation',
      'http://hl7.org/fhir/StructureDefinition/bp',
      'http://hl7.org/fhir/StructureDefinition/bodyheight',
      'http://hl7.org/fhir/StructureDefinition/bmi',
      'http://hl7.org/fhir/StructureDefinition/bodytemp',
      'http://hl7.org/fhir/StructureDefinition/bodyweight',
      'http://hl7.org/fhir/StructureDefinition/heartrate',
      'http://hl7.org/fhir/StructureDefinition/oxygensat',
      'http://hl7.org/fhir/StructureDefinition/resprate',
    ],
  },
} as const

export const groveFhirPackageCanonicals = {
  mobile: 'https://grovealliance.org/fhir/mobile',
  questionnaire: 'https://grovealliance.org/fhir/questionnaire',
  sensor: 'https://grovealliance.org/fhir/sensor',
  healthkit: 'https://grovealliance.org/fhir/healthkit',
  'health-connect': 'https://grovealliance.org/fhir/health-connect',
  'connected-health': 'https://grovealliance.org/fhir/connected-health',
} as const

export const groveFhirProfileCanonicals = {
  'grove-application-device':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-application-device',
  'grove-mobile-active-energy':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-active-energy',
  'grove-mobile-basal-body-temperature':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-basal-body-temperature',
  'grove-mobile-blood-glucose':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-blood-glucose',
  'grove-mobile-blood-pressure':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-blood-pressure',
  'grove-mobile-bmi':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-bmi',
  'grove-mobile-body-height':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-height',
  'grove-mobile-body-temperature':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-temperature',
  'grove-mobile-body-weight':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-weight',
  'grove-mobile-capillary-blood-glucose':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-capillary-blood-glucose',
  'grove-mobile-conversion-provenance':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-conversion-provenance',
  'grove-mobile-distance':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-distance',
  'grove-mobile-exchange-bundle':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-exchange-bundle',
  'grove-mobile-heart-rate':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-heart-rate',
  'grove-mobile-interstitial-glucose':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-interstitial-glucose',
  'grove-mobile-observation':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-observation',
  'grove-mobile-oxygen-saturation':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-oxygen-saturation',
  'grove-mobile-respiratory-rate':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-respiratory-rate',
  'grove-mobile-serum-plasma-glucose':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-serum-plasma-glucose',
  'grove-mobile-sleep-duration':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-duration',
  'grove-mobile-sleep-stage':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-stage',
  'grove-mobile-step-count':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-step-count',
  'grove-recording-device':
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-recording-device',
  'grove-questionnaire':
    'https://grovealliance.org/fhir/questionnaire/StructureDefinition/grove-questionnaire',
  'grove-questionnaire-response':
    'https://grovealliance.org/fhir/questionnaire/StructureDefinition/grove-questionnaire-response',
  'grove-sensor-ecg-observation':
    'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-ecg-observation',
  'grove-sensor-recording-document':
    'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document',
  'grove-sensor-sampled-data-observation':
    'https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-sampled-data-observation',
  'healthkit-observation':
    'https://grovealliance.org/fhir/healthkit/StructureDefinition/healthkit-observation',
  'health-connect-conversion-provenance':
    'https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-conversion-provenance',
  'health-connect-observation':
    'https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-observation',
  'connected-health-conversion-provenance':
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-conversion-provenance',
  'connected-health-observation':
    'https://grovealliance.org/fhir/connected-health/StructureDefinition/connected-health-observation',
} as const

export const implementedMeasurementCatalog = {
  'active-energy': {
    id: 'active-energy',
    profile: 'grove-mobile-active-energy',
    standardProfile: null,
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'active-energy-burned',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'kcal',
    },
    effective: 'Period',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'basal-body-temperature': {
    id: 'basal-body-temperature',
    profile: 'grove-mobile-basal-body-temperature',
    standardProfile: null,
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'basal-body-temperature',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'Cel',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'deferred',
      oura: 'provider-specific',
      withings: 'deferred',
    },
  },
  'blood-glucose': {
    id: 'blood-glucose',
    profile: 'grove-mobile-blood-glucose',
    standardProfile: null,
    code: {
      system: 'http://loinc.org',
      code: '2339-0',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'mg/dL',
    },
    specimen: {
      system: 'http://snomed.info/sct',
      code: '258580003',
      display: 'Whole blood sample',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'deferred',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'deferred',
    },
  },
  'capillary-blood-glucose': {
    id: 'capillary-blood-glucose',
    profile: 'grove-mobile-capillary-blood-glucose',
    standardProfile: null,
    code: {
      system: 'http://loinc.org',
      code: '32016-8',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'mg/dL',
    },
    specimen: {
      system: 'http://snomed.info/sct',
      code: '122554006',
      display: 'Capillary blood specimen',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'deferred',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'deferred',
    },
  },
  'serum-plasma-glucose': {
    id: 'serum-plasma-glucose',
    profile: 'grove-mobile-serum-plasma-glucose',
    standardProfile: null,
    code: {
      system: 'http://loinc.org',
      code: '2345-7',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'mg/dL',
    },
    specimenAlternatives: [
      {
        id: 'plasma',
        system: 'http://snomed.info/sct',
        code: '119361006',
        display: 'Plasma specimen',
      },
      {
        id: 'serum',
        system: 'http://snomed.info/sct',
        code: '119364003',
        display: 'Serum specimen',
      },
    ],
    effective: 'dateTime',
    coverage: {
      healthkit: 'deferred',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'deferred',
    },
  },
  'interstitial-glucose': {
    id: 'interstitial-glucose',
    profile: 'grove-mobile-interstitial-glucose',
    standardProfile: null,
    code: {
      system: 'http://loinc.org',
      code: '99504-3',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'mg/dL',
    },
    specimen: {
      system: 'http://snomed.info/sct',
      code: '258479004',
      display: 'Interstitial fluid specimen',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'deferred',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'deferred',
    },
  },
  'blood-pressure': {
    id: 'blood-pressure',
    profile: 'grove-mobile-blood-pressure',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bp',
    code: {
      system: 'http://loinc.org',
      code: '85354-9',
    },
    components: [
      {
        id: 'systolic',
        system: 'http://loinc.org',
        code: '8480-6',
        quantity: {
          system: 'http://unitsofmeasure.org',
          code: 'mm[Hg]',
        },
      },
      {
        id: 'diastolic',
        system: 'http://loinc.org',
        code: '8462-4',
        quantity: {
          system: 'http://unitsofmeasure.org',
          code: 'mm[Hg]',
        },
      },
    ],
    quantity: null,
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'supported',
    },
  },
  'body-height': {
    id: 'body-height',
    profile: 'grove-mobile-body-height',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodyheight',
    code: {
      system: 'http://loinc.org',
      code: '8302-2',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'cm',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'supported',
    },
  },
  'body-mass-index': {
    id: 'body-mass-index',
    profile: 'grove-mobile-bmi',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bmi',
    code: {
      system: 'http://loinc.org',
      code: '39156-5',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'kg/m2',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'intentionally-unsupported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'supported',
    },
  },
  'body-temperature': {
    id: 'body-temperature',
    profile: 'grove-mobile-body-temperature',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodytemp',
    code: {
      system: 'http://loinc.org',
      code: '8310-5',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'Cel',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'provider-specific',
      'google-health-api': 'supported',
      oura: 'provider-specific',
      withings: 'supported',
    },
  },
  'body-weight': {
    id: 'body-weight',
    profile: 'grove-mobile-body-weight',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodyweight',
    code: {
      system: 'http://loinc.org',
      code: '29463-7',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'kg',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'intentionally-unsupported',
      withings: 'supported',
    },
  },
  distance: {
    id: 'distance',
    profile: 'grove-mobile-distance',
    standardProfile: null,
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'distance-traveled',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'm',
    },
    effective: 'Period',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'mapped-standard',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'heart-rate': {
    id: 'heart-rate',
    profile: 'grove-mobile-heart-rate',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/heartrate',
    code: {
      system: 'http://loinc.org',
      code: '8867-4',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '/min',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'supported',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'oxygen-saturation': {
    id: 'oxygen-saturation',
    profile: 'grove-mobile-oxygen-saturation',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/oxygensat',
    code: {
      system: 'http://loinc.org',
      code: '2708-6',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '%',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'respiratory-rate': {
    id: 'respiratory-rate',
    profile: 'grove-mobile-respiratory-rate',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/resprate',
    code: {
      system: 'http://loinc.org',
      code: '9279-1',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '/min',
    },
    effective: 'dateTime',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'intentionally-unsupported',
      'google-health-api': 'supported',
      oura: 'mapped-standard',
      withings: 'supported',
    },
  },
  'sleep-duration': {
    id: 'sleep-duration',
    profile: 'grove-mobile-sleep-duration',
    standardProfile: null,
    code: {
      system: 'http://loinc.org',
      code: '93832-4',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'h',
    },
    effective: 'Period',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'mapped-standard',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'sleep-stage': {
    id: 'sleep-stage',
    profile: 'grove-mobile-sleep-stage',
    standardProfile: null,
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'sleep-stage',
    },
    quantity: null,
    valueSet:
      'https://grovealliance.org/fhir/mobile/ValueSet/grove-sleep-stage',
    resultCodeSystem:
      'https://grovealliance.org/fhir/mobile/CodeSystem/grove-sleep-stage',
    allowedValues: [
      'awake',
      'in-bed',
      'out-of-bed',
      'asleep-unspecified',
      'light',
      'deep',
      'rem',
      'unknown',
    ],
    effective: 'Period',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'mapped-standard',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
  'step-count': {
    id: 'step-count',
    profile: 'grove-mobile-step-count',
    standardProfile: null,
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'step-count-total',
    },
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '{steps}',
    },
    effective: 'Period',
    coverage: {
      healthkit: 'supported',
      'health-connect': 'supported',
      sensorkit: 'supported',
      'google-health-api': 'supported',
      oura: 'supported',
      withings: 'supported',
    },
  },
} as const

export type ImplementedMeasurementKind =
  keyof typeof implementedMeasurementCatalog
