//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate-measurement-catalog.mjs. Do not edit directly.

/* eslint-disable sonarjs/no-clear-text-protocols */

import { deepFreeze } from '../core/index.js'

export const groveFhirContractVersion = '0.2.0' as const

export const groveFhirVersion = '4.0.1' as const

const groveMobilePackageMetadataValue = {
  fhirVersion: '4.0.1',
  version: '0.2.0',
  packageId: 'org.grovealliance.fhir.mobile',
  canonical: 'https://grovealliance.org/fhir/mobile',
  dependencies: ['hl7.terminology.r4#7.3.0', 'hl7.fhir.uv.extensions.r4#5.3.0'],
} as const

export const groveMobilePackageMetadata: typeof groveMobilePackageMetadataValue =
  deepFreeze(groveMobilePackageMetadataValue)

const groveFhirExchangeIdentityValue = {
  schemaVersion: 1,
  version: '0.2.0',
  fhirVersion: '4.0.1',
  profile:
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-exchange-bundle',
  entryIdentifierExtension:
    'https://grovealliance.org/fhir/mobile/StructureDefinition/grove-exchange-entry-identifier',
  fullUrlAlgorithm: {
    name: 'uuid-v5-jcs-identifier-v1',
    namespace: 'a9a39cf1-c944-5d15-a3c2-c395969ea101',
    input:
      'UTF-8 bytes of the RFC 8785 JSON Canonicalization Scheme serialization of exactly [system,value]',
    stringRules: {
      unicode:
        'system and value MUST contain only Unicode scalar values; isolated UTF-16 surrogates are rejected',
      escaping:
        'escape quotation mark and reverse solidus; use the two-character escapes \\b, \\t, \\n, \\f and \\r; encode every other U+0000 through U+001F control as lowercase \\u00xx; do not escape solidus or any other scalar value',
      encoding:
        'encode the resulting JSON text as UTF-8 without a byte-order mark',
      array:
        'quotation mark, serialized system, quotation mark, comma, quotation mark, serialized value, quotation mark; no whitespace',
    },
    output: 'urn:uuid:<lowercase RFC 4122 UUID version 5>',
  },
  resourceId: {
    role: 'repository logical id',
    required: false,
    sourceIdentityAllowed: false,
  },
  internalReferences: {
    containedReferencesAllowed: true,
    bundleEntryReferences: 'must use an entry fullUrl UUID URN',
    unresolvedUuidUrnsAllowed: false,
  },
  vectors: [
    {
      case: 'ascii',
      system: 'https://study.example.org/fhir/identifiers/mobile-observation',
      value: 'heart-rate-20260820-001',
      input:
        '["https://study.example.org/fhir/identifiers/mobile-observation","heart-rate-20260820-001"]',
      fullUrl: 'urn:uuid:cd27941b-2a75-5f7a-bd25-71e9480eac24',
    },
    {
      case: 'quotation-mark-and-reverse-solidus',
      system: 'https://example.org/"quoted"',
      value: 'back\\slash',
      input: '["https://example.org/\\"quoted\\"","back\\\\slash"]',
      fullUrl: 'urn:uuid:fe6c20ac-f147-5322-8804-c09d5c0f62d6',
    },
    {
      case: 'control-characters',
      system: 'https://example.org/control',
      value: 'line\nfeed\u0001',
      input: '["https://example.org/control","line\\nfeed\\u0001"]',
      fullUrl: 'urn:uuid:9a1a6b19-a138-5fdf-8954-68a3da142c64',
    },
    {
      case: 'non-ascii',
      system: 'https://例.example/識別子',
      value: 'café-東京',
      input: '["https://例.example/識別子","café-東京"]',
      fullUrl: 'urn:uuid:f1395804-98e2-5d14-a2f4-cbe93380ee7a',
    },
  ],
} as const

export const groveFhirExchangeIdentity: typeof groveFhirExchangeIdentityValue =
  deepFreeze(groveFhirExchangeIdentityValue)

const sharedMobileMeasurementCatalogValue = {
  'active-energy': {
    id: 'active-energy',
    profile: 'grove-mobile-active-energy',
    standardProfile: null,
    title: 'Grove Mobile Active Energy',
    description:
      'Activity-related energy expenditure, excluding basal energy, during an exact effective Period and normalized to UCUM kilocalories.',
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'active-energy-burned',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'kcal',
      unit: 'kcal',
      dimension: {
        g: 1,
        m: 2,
        s: -2,
      },
    },
    effective: 'Period',
  },
  'basal-body-temperature': {
    id: 'basal-body-temperature',
    profile: 'grove-mobile-basal-body-temperature',
    standardProfile: null,
    title: 'Grove Mobile Basal Body Temperature',
    description:
      'A source-neutral basal body temperature recorded at physiologic rest and normalized to UCUM degrees Celsius. It is not the general body-temperature vital sign.',
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'basal-body-temperature',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'Cel',
      unit: 'Cel',
      dimension: {
        K: 1,
      },
    },
    effective: 'dateTime',
  },
  'blood-pressure': {
    id: 'blood-pressure',
    profile: 'grove-mobile-blood-pressure',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bp',
    title: 'Grove Mobile Blood Pressure',
    description:
      'A source-neutral mobile blood-pressure panel that is required to conform to the authoritative FHIR R4 Blood Pressure profile. Systolic and diastolic components are normalized to UCUM millimetres of mercury.',
    code: {
      system: 'http://loinc.org',
      code: '85354-9',
    },
    valueKind: 'components',
    components: [
      {
        id: 'systolic',
        system: 'http://loinc.org',
        code: '8480-6',
        quantity: {
          system: 'http://unitsofmeasure.org',
          code: 'mm[Hg]',
          unit: 'mmHg',
          dimension: {
            g: 1,
            m: -1,
            s: -2,
          },
        },
      },
      {
        id: 'diastolic',
        system: 'http://loinc.org',
        code: '8462-4',
        quantity: {
          system: 'http://unitsofmeasure.org',
          code: 'mm[Hg]',
          unit: 'mmHg',
          dimension: {
            g: 1,
            m: -1,
            s: -2,
          },
        },
      },
    ],
    quantity: null,
    effective: 'dateTime',
  },
  'body-height': {
    id: 'body-height',
    profile: 'grove-mobile-body-height',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodyheight',
    title: 'Grove Mobile Body Height',
    description:
      'A source-neutral mobile body height that is required to conform to the authoritative FHIR R4 Body Height profile. Values are normalized to UCUM centimetres.',
    code: {
      system: 'http://loinc.org',
      code: '8302-2',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'cm',
      unit: 'cm',
      dimension: {
        m: 1,
      },
    },
    effective: 'dateTime',
  },
  'body-temperature': {
    id: 'body-temperature',
    profile: 'grove-mobile-body-temperature',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodytemp',
    title: 'Grove Mobile Body Temperature',
    description:
      'A source-neutral mobile body temperature that is required to conform to the authoritative FHIR R4 Body Temperature profile. Values are normalized to UCUM degrees Celsius.',
    code: {
      system: 'http://loinc.org',
      code: '8310-5',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'Cel',
      unit: 'Cel',
      dimension: {
        K: 1,
      },
    },
    effective: 'dateTime',
  },
  'body-weight': {
    id: 'body-weight',
    profile: 'grove-mobile-body-weight',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/bodyweight',
    title: 'Grove Mobile Body Weight',
    description:
      'A source-neutral mobile body weight that is required to conform to the authoritative FHIR R4 Body Weight profile. Values are normalized to UCUM kilograms.',
    code: {
      system: 'http://loinc.org',
      code: '29463-7',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'kg',
      unit: 'kg',
      dimension: {
        g: 1,
      },
    },
    effective: 'dateTime',
  },
  distance: {
    id: 'distance',
    profile: 'grove-mobile-distance',
    standardProfile: null,
    title: 'Grove Mobile Distance',
    description:
      'Distance traveled during an exact effective Period, normalized to UCUM metres.',
    code: {
      system: 'http://loinc.org',
      code: '103208-5',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'm',
      unit: 'm',
      dimension: {
        m: 1,
      },
    },
    effective: 'Period',
  },
  'heart-rate': {
    id: 'heart-rate',
    profile: 'grove-mobile-heart-rate',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/heartrate',
    title: 'Grove Mobile Heart Rate',
    description:
      'A source-neutral mobile heart rate that is required to conform to the authoritative FHIR R4 Heart Rate profile and adds Grove exchange identity and provenance context. Values are normalized to UCUM beats per minute.',
    code: {
      system: 'http://loinc.org',
      code: '8867-4',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '/min',
      unit: 'beats/minute',
      dimension: {
        s: -1,
      },
    },
    effective: 'dateTime',
  },
  'oxygen-saturation': {
    id: 'oxygen-saturation',
    profile: 'grove-mobile-oxygen-saturation',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/oxygensat',
    title: 'Grove Mobile Oxygen Saturation',
    description:
      'A source-neutral mobile oxygen saturation that is required to conform to the authoritative FHIR R4 Oxygen Saturation profile. Values are normalized to UCUM percent.',
    code: {
      system: 'http://loinc.org',
      code: '2708-6',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '%',
      unit: '%',
      dimension: {},
    },
    effective: 'dateTime',
  },
  'respiratory-rate': {
    id: 'respiratory-rate',
    profile: 'grove-mobile-respiratory-rate',
    standardProfile: 'http://hl7.org/fhir/StructureDefinition/resprate',
    title: 'Grove Mobile Respiratory Rate',
    description:
      'A source-neutral mobile respiratory rate that is required to conform to the authoritative FHIR R4 Respiratory Rate profile. Values are normalized to breaths per minute.',
    code: {
      system: 'http://loinc.org',
      code: '9279-1',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '/min',
      unit: 'breaths/minute',
      dimension: {
        s: -1,
      },
    },
    effective: 'dateTime',
  },
  'sleep-duration': {
    id: 'sleep-duration',
    profile: 'grove-mobile-sleep-duration',
    standardProfile: null,
    title: 'Grove Mobile Sleep Duration',
    description:
      'Total duration classified as sleep during an exact effective Period, using LOINC Sleep duration and normalized to UCUM hours. This summary does not encode sleep stages.',
    code: {
      system: 'http://loinc.org',
      code: '93832-4',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: 'h',
      unit: 'h',
      dimension: {
        s: 1,
      },
    },
    effective: 'Period',
    hasMember: ['sleep-stage'],
  },
  'sleep-stage': {
    id: 'sleep-stage',
    profile: 'grove-mobile-sleep-stage',
    standardProfile: null,
    title: 'Grove Mobile Sleep Stage',
    description:
      'A source-neutral sleep-stage classification for one exact interval. A session summary links its ordered, non-overlapping stage Observations through hasMember.',
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'sleep-stage',
    },
    valueKind: 'codeableConcept',
    quantity: null,
    valueSet:
      'https://grovealliance.org/fhir/mobile/ValueSet/grove-sleep-stage',
    resultCodeSystem:
      'https://grovealliance.org/fhir/mobile/CodeSystem/grove-sleep-stage',
    allowedValues: [
      'awake',
      'in-bed',
      'out-of-bed',
      'asleep-unspecified',
      'light',
      'deep',
      'rem',
      'unknown',
    ],
    effective: 'Period',
  },
  'step-count': {
    id: 'step-count',
    profile: 'grove-mobile-step-count',
    standardProfile: null,
    title: 'Grove Mobile Step Count',
    description:
      'The number of steps recorded during an exact effective Period.',
    code: {
      system:
        'https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement',
      code: 'step-count-total',
    },
    valueKind: 'quantity',
    quantity: {
      system: 'http://unitsofmeasure.org',
      code: '{steps}',
      unit: 'steps',
      dimension: {},
      unitMustSupport: true,
    },
    effective: 'Period',
    obeys: [
      'grove-step-count-result-1',
      'grove-step-count-period-1',
      'grove-step-count-value-1',
    ],
  },
} as const

export const sharedMobileMeasurementCatalog: typeof sharedMobileMeasurementCatalogValue =
  deepFreeze(sharedMobileMeasurementCatalogValue)

const mobileEffectiveCanonicalizationValue = {
  scope:
    'Every Mobile scalar or aggregate effectiveDateTime and effectivePeriod endpoint; Sensor and ECG SampledData timing is excluded.',
  precision: 'millisecond',
  rounding: 'half-even',
  epoch: '1970-01-01T00:00:00Z',
  offsetPolicy:
    'Preserve the caller/source numeric UTC offset when it is available; never invent an offset.',
} as const

export const mobileEffectiveCanonicalization: typeof mobileEffectiveCanonicalizationValue =
  deepFreeze(mobileEffectiveCanonicalizationValue)

const mobileEffectiveCanonicalizationVectorsValue = [
  {
    id: 'positive-below-half',
    input: '1970-01-01T00:00:00.000499999Z',
    output: '1970-01-01T00:00:00.000Z',
  },
  {
    id: 'positive-half-to-even',
    input: '1970-01-01T00:00:00.000500000Z',
    output: '1970-01-01T00:00:00.000Z',
  },
  {
    id: 'positive-half-to-next-even',
    input: '1970-01-01T00:00:00.001500000Z',
    output: '1970-01-01T00:00:00.002Z',
  },
  {
    id: 'negative-half-to-even',
    input: '1969-12-31T23:59:59.999500000Z',
    output: '1970-01-01T00:00:00.000Z',
  },
  {
    id: 'negative-half-to-previous-even',
    input: '1969-12-31T23:59:59.998500000Z',
    output: '1969-12-31T23:59:59.998Z',
  },
  {
    id: 'offset-preserved',
    input: '2026-08-20T08:30:00.251499999-07:00',
    output: '2026-08-20T08:30:00.251-07:00',
  },
] as const

export const mobileEffectiveCanonicalizationVectors: typeof mobileEffectiveCanonicalizationVectorsValue =
  deepFreeze(mobileEffectiveCanonicalizationVectorsValue)

export type SharedMobileMeasurementKind =
  keyof typeof sharedMobileMeasurementCatalog
