//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const RELEASES = ['r4', 'r4b'] as const

/** The invariants each pinned release states that the generator does not check. */
const UNCHECKED_KEYS: Readonly<Record<string, readonly string[]>> = {
  r4: [
    'adf-0',
    'age-1',
    'ait-1',
    'ait-2',
    'app-1',
    'app-2',
    'app-3',
    'app-4',
    'apr-1',
    'att-1',
    'bdl-1',
    'bdl-10',
    'bdl-11',
    'bdl-12',
    'bdl-2',
    'bdl-3',
    'bdl-4',
    'bdl-5',
    'bdl-7',
    'bdl-8',
    'bdl-9',
    'ces-1',
    'cid-0',
    'cmd-0',
    'cmd-1',
    'cmd-2',
    'cmd-3',
    'cmp-1',
    'cmp-2',
    'cnt-3',
    'con-1',
    'con-2',
    'con-3',
    'con-4',
    'con-5',
    'cpb-0',
    'cpb-1',
    'cpb-12',
    'cpb-14',
    'cpb-15',
    'cpb-16',
    'cpb-2',
    'cpb-3',
    'cpb-7',
    'cpb-9',
    'cpd-0',
    'cpl-3',
    'cpt-2',
    'csd-0',
    'csd-1',
    'ctm-1',
    'dis-1',
    'dom-2',
    'dom-3',
    'dom-4',
    'dom-5',
    'dom-6',
    'drq-1',
    'drq-2',
    'drt-1',
    'ees-0',
    'eld-1',
    'eld-11',
    'eld-12',
    'eld-13',
    'eld-14',
    'eld-15',
    'eld-16',
    'eld-17',
    'eld-18',
    'eld-19',
    'eld-2',
    'eld-20',
    'eld-21',
    'eld-22',
    'eld-3',
    'eld-4',
    'eld-5',
    'eld-6',
    'eld-7',
    'eld-8',
    'esc-0',
    'evd-0',
    'evi-0',
    'evv-0',
    'exp-1',
    'fhs-1',
    'fhs-2',
    'gdf-0',
    'gol-1',
    'grp-1',
    'ig-0',
    'ig-1',
    'ig-2',
    'imm-1',
    'imr-1',
    'inv-1',
    'inv-2',
    'ipn-1',
    'lib-0',
    'lnk-1',
    'lst-1',
    'lst-2',
    'lst-3',
    'mad-1',
    'md-1',
    'mdd-1',
    'mea-0',
    'mea-1',
    'mrp-1',
    'mrp-2',
    'msd-0',
    'msq-3',
    'msq-5',
    'msq-6',
    'nor-1',
    'nsd-0',
    'nsd-1',
    'nsd-2',
    'obs-7',
    'opd-0',
    'opd-1',
    'opd-2',
    'opd-3',
    'org-1',
    'org-2',
    'org-3',
    'pat-1',
    'pdf-0',
    'ppc-1',
    'ppc-2',
    'ppc-3',
    'ppc-4',
    'ppc-5',
    'prr-1',
    'qrs-1',
    'qty-3',
    'que-0',
    'que-1',
    'que-10',
    'que-11',
    'que-12',
    'que-13',
    'que-2',
    'que-3',
    'que-4',
    'que-5',
    'que-6',
    'que-7',
    'que-8',
    'que-9',
    'ras-1',
    'ras-2',
    'rat-1',
    'red-0',
    'ref-1',
    'rng-2',
    'rqg-1',
    'rsd-0',
    'rvs-0',
    'sdf-0',
    'sdf-1',
    'sdf-10',
    'sdf-11',
    'sdf-14',
    'sdf-15',
    'sdf-16',
    'sdf-17',
    'sdf-18',
    'sdf-19',
    'sdf-2',
    'sdf-20',
    'sdf-21',
    'sdf-22',
    'sdf-23',
    'sdf-3',
    'sdf-4',
    'sdf-5',
    'sdf-6',
    'sdf-8',
    'sdf-9',
    'sev-1',
    'smp-0',
    'smp-1',
    'smp-2',
    'spd-0',
    'spd-1',
    'spd-2',
    'tcp-0',
    'tcp-1',
    'tcp-2',
    'tcp-3',
    'tcp-4',
    'tcp-5',
    'tim-1',
    'tim-10',
    'tim-2',
    'tim-4',
    'tim-5',
    'tim-6',
    'tim-7',
    'tim-8',
    'tim-9',
    'trd-1',
    'trd-2',
    'trd-3',
    'tst-0',
    'tst-1',
    'tst-10',
    'tst-11',
    'tst-12',
    'tst-13',
    'tst-2',
    'tst-3',
    'tst-4',
    'tst-5',
    'tst-6',
    'tst-7',
    'tst-8',
    'tst-9',
    'txt-1',
    'txt-2',
    'vsd-0',
    'vsd-1',
    'vsd-10',
    'vsd-2',
    'vsd-3',
    'vsd-6',
    'vsd-9',
  ],
  r4b: [
    'age-1',
    'ait-1',
    'ait-2',
    'apd-1',
    'app-1',
    'app-2',
    'app-3',
    'app-4',
    'apr-1',
    'att-1',
    'bdl-1',
    'bdl-10',
    'bdl-11',
    'bdl-12',
    'bdl-2',
    'bdl-3',
    'bdl-4',
    'bdl-5',
    'bdl-7',
    'bdl-8',
    'bdl-9',
    'ces-1',
    'cid-0',
    'cmd-0',
    'cmd-1',
    'cmd-2',
    'cmd-3',
    'cmp-1',
    'cmp-2',
    'cnl-0',
    'cnt-3',
    'con-1',
    'con-2',
    'con-3',
    'con-4',
    'con-5',
    'cpb-0',
    'cpb-1',
    'cpb-12',
    'cpb-14',
    'cpb-15',
    'cpb-16',
    'cpb-2',
    'cpb-3',
    'cpb-7',
    'cpb-9',
    'cpd-0',
    'cpl-3',
    'cpt-2',
    'csd-0',
    'csd-1',
    'ctm-1',
    'cud-1',
    'dis-1',
    'dom-2',
    'dom-3',
    'dom-4',
    'dom-5',
    'dom-6',
    'drq-1',
    'drq-2',
    'drt-1',
    'eld-1',
    'eld-11',
    'eld-12',
    'eld-13',
    'eld-14',
    'eld-15',
    'eld-16',
    'eld-17',
    'eld-18',
    'eld-19',
    'eld-2',
    'eld-20',
    'eld-21',
    'eld-22',
    'eld-3',
    'eld-4',
    'eld-5',
    'eld-6',
    'eld-7',
    'eld-8',
    'esc-0',
    'evd-0',
    'exp-1',
    'fhs-1',
    'fhs-2',
    'gdf-0',
    'gol-1',
    'grp-1',
    'ig-0',
    'ig-1',
    'ig-2',
    'imm-1',
    'imr-1',
    'ing-1',
    'inv-1',
    'inv-2',
    'ipn-1',
    'lnk-1',
    'lst-1',
    'lst-2',
    'lst-3',
    'mad-1',
    'md-1',
    'mdd-1',
    'mea-1',
    'mrp-1',
    'mrp-2',
    'msd-0',
    'msq-3',
    'msq-5',
    'msq-6',
    'nor-1',
    'nsd-0',
    'nsd-1',
    'nsd-2',
    'obs-7',
    'opd-0',
    'opd-1',
    'opd-2',
    'opd-3',
    'org-1',
    'org-2',
    'org-3',
    'pat-1',
    'ppc-1',
    'ppc-2',
    'ppc-3',
    'ppc-4',
    'ppc-5',
    'prr-1',
    'qrs-1',
    'qty-3',
    'que-0',
    'que-10',
    'que-11',
    'que-12',
    'que-13',
    'que-2',
    'que-3',
    'que-4',
    'que-5',
    'que-6',
    'que-7',
    'que-8',
    'que-9',
    'ras-1',
    'ras-2',
    'rat-1',
    'red-0',
    'ref-1',
    'rng-2',
    'rqg-1',
    'rsd-0',
    'sdf-0',
    'sdf-1',
    'sdf-10',
    'sdf-11',
    'sdf-14',
    'sdf-15',
    'sdf-16',
    'sdf-17',
    'sdf-18',
    'sdf-19',
    'sdf-2',
    'sdf-20',
    'sdf-21',
    'sdf-22',
    'sdf-23',
    'sdf-24',
    'sdf-25',
    'sdf-3',
    'sdf-4',
    'sdf-5',
    'sdf-6',
    'sdf-8',
    'sdf-9',
    'sev-1',
    'smp-0',
    'smp-1',
    'smp-2',
    'spd-0',
    'spd-1',
    'spd-2',
    'sst-1',
    'tcp-0',
    'tcp-1',
    'tcp-2',
    'tcp-3',
    'tcp-4',
    'tcp-5',
    'tim-1',
    'tim-10',
    'tim-2',
    'tim-4',
    'tim-5',
    'tim-6',
    'tim-7',
    'tim-8',
    'tim-9',
    'trd-1',
    'trd-2',
    'trd-3',
    'tst-0',
    'tst-1',
    'tst-10',
    'tst-11',
    'tst-12',
    'tst-13',
    'tst-2',
    'tst-3',
    'tst-4',
    'tst-5',
    'tst-6',
    'tst-7',
    'tst-8',
    'tst-9',
    'txt-1',
    'txt-2',
    'vsd-0',
    'vsd-1',
    'vsd-10',
    'vsd-2',
    'vsd-3',
    'vsd-6',
    'vsd-9',
  ],
}

const source = (release: string): string =>
  readFileSync(join(process.cwd(), 'src/zod', release, 'schemas.ts'), 'utf8')

describe.each(RELEASES)('generated %s schemas', (release) => {
  const text = source(release)

  it('leaves no element unvalidated', () => {
    // An escape to z.unknown() means an element lost its constraint; every one of these was a
    // real gap when the generator was written.
    expect(text).not.toContain('z.unknown()')
  })

  it('states a type for every exported schema', () => {
    // Without the annotation the schema is only cast to the release's type, never checked
    // against it, and a mismatch reaches consumers as a silent `any`.
    const untyped = [...text.matchAll(/^export const (\w+Schema)(?!: )/gm)].map(
      (m) => m[1],
    )
    expect(untyped).toEqual([])
  })

  it('rejects properties the release does not define', () => {
    // FHIR JSON is closed; a plain object would strip an unmodelled property silently.
    expect(text).not.toMatch(/z\.object\(/)
    expect(text).toContain('z.strictObject(')
  })

  it('keeps the extensions a primitive may carry', () => {
    // Every primitive-valued element has a `_`-prefixed sibling for its id and extensions.
    expect((text.match(/(?:^|\s)_[A-Za-z]\w*:/g) ?? []).length).toBeGreaterThan(
      300,
    )
  })

  it('closes every required binding it can enumerate', () => {
    expect((text.match(/z\.enum\(/g) ?? []).length).toBeGreaterThan(30)
  })

  it('constrains the primitives the release gives a pattern', () => {
    expect((text.match(/new RegExp\(/g) ?? []).length).toBeGreaterThan(10)
  })

  it('enforces the invariants the release states', () => {
    for (const message of [
      'ext-1',
      'obs-6',
      'Period.start must not be later',
    ]) {
      expect(text).toContain(message)
    }
    expect(text).toContain(
      'A choice element carries exactly one alternative when required, and at most one otherwise.',
    )
  })

  it('publishes the invariants it does not check', () => {
    // A validator that silently ignores an invariant overstates itself. The map makes the gap
    // inspectable, and this assertion makes a new release's new invariants fail the build
    // rather than disappear.
    expect(text).toContain('export const UNCHECKED_CONSTRAINTS')
    const map = text.slice(text.indexOf('UNCHECKED_CONSTRAINTS'))
    const keys = new Set(
      [...(map.match(/'[a-z]+-\d+'/g) ?? [])].map((key) => key.slice(1, -1)),
    )
    // Pinned, not bounded: these are facts about a pinned release, so a release that states a
    // new invariant must fail here rather than silently widening the gap.
    expect([...keys].sort((a, b) => a.localeCompare(b))).toEqual(
      UNCHECKED_KEYS[release],
    )
    // Anything implemented must not also be reported as unchecked.
    for (const implemented of ['ext-1', 'per-1', 'obs-3', 'obs-6']) {
      expect(keys.has(implemented)).toBe(false)
    }
  })

  it('is generated, and says so', () => {
    expect(text).toContain('GENERATED FILE')
    expect(text).toMatch(/Generated from hl7\.fhir\.\w+\.core#/)
  })
})

describe('release coverage', () => {
  it('covers both releases from one generator', () => {
    // R4B is a minimal delta over R4 for this surface; if that stops being true the generator is
    // producing something release-specific that deserves a look.
    const r4 = source('r4').split('\n').length
    const r4b = source('r4b').split('\n').length
    expect(Math.abs(r4b - r4)).toBeLessThan(r4 * 0.1)
  })
})
