//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate-measurement-catalog.mjs. Do not edit directly.

import { deepFreeze } from '../core/index.js'

export const groveFhirVersion = '4.0.1' as const

const groveQuestionnairePackageMetadataValue = {
  fhirVersion: '4.0.1',
  version: '0.6.0',
  packageId: 'org.grovealliance.fhir.questionnaire',
  canonical: 'https://grovealliance.org/fhir/questionnaire',
  dependencies: ['hl7.fhir.uv.sdc#4.0.0', 'hl7.fhir.uv.extensions.r4#5.3.0'],
} as const

export const groveQuestionnairePackageMetadata: typeof groveQuestionnairePackageMetadataValue =
  deepFreeze(groveQuestionnairePackageMetadataValue)

const groveQuestionnaireProfileCanonicalsValue = {
  'grove-questionnaire':
    'https://grovealliance.org/fhir/questionnaire/StructureDefinition/grove-questionnaire',
  'grove-questionnaire-response':
    'https://grovealliance.org/fhir/questionnaire/StructureDefinition/grove-questionnaire-response',
} as const

export const groveQuestionnaireProfileCanonicals: typeof groveQuestionnaireProfileCanonicalsValue =
  deepFreeze(groveQuestionnaireProfileCanonicalsValue)
